### PR TITLE
Refactoring: bring in line with Stackable java set-up

### LINKED ISSUE #325: Add support for HDFS rack awareness feature
We should add support for HDFS' rack awareness feature to the HDFS operator.

This cannot be achieved via config overrides, as the config setting takes a script which has to return the rack based on hostname and ip address of the datanode.

Some ideas that have been put forward for this are: 

1. Ship kubectl with the hdfs image and do something like this: 
`kubectl get node $(kubectl get pod <hostname> -o yaml | jq ".status.node") -o yaml | yq ''.metadata.labels."[kubernetes.io/rack](http://kubernetes.io/rack)
`
2. Mount a configmap in the namenode somewhere and have a fixed script configured that does a lookup in a textfile in that configmap. This configmap could then be updated by the hdfs operator.
3. Have a sidecar-container in the hdfs namenode that periodically polls the racks of the datanodes and writes that into a shared emptyDir. That emptyDir can be easily used by the main container
```[tasklist]
### Tasks
- [ ] documentation for the feature needs to be added
```

### PR DESCRIPTION
**Pull request by adwk67**
Based on template introduced in https://github.com/stackabletech/hdfs-group-mapper

### CODE REVIEW

**Review by soenkeliebau — APPROVED** [review]
looks good to me overall, but there is far too much stuff here for me to actually look at in detail I am afraid. I'll trust that this is in line with what @lfrancke considers best practice.

Just one comment, should we introduce profiles to check compatibility with Hadoop versions at this point as well, like in the Druid authorizer?

https://github.com/stackabletech/druid-opa-authorizer/blob/main/.github/workflows/maven.yml#L22

https://github.com/stackabletech/druid-opa-authorizer/blob/main/pom.xml#L313

**Comment by lfrancke** [comment]
It's looking good to me! A lot of duplication but we can tackle that later (e.g. java-templating and a parent POM).

The profiles with compatibility would be nice but I'm happy to keep that separate.

**Comment by adwk67** [comment]
One thing I noticed when using the changes in hdfs-group-mapper was that the IDE indentation used by @lfrancke was/is 2 spaces (I had 4 as a default). How can we sensibly enforce that, bearing in mind folks use different IDEs? (maybe that's in one of those plugins and I just missed it).

**Comment by soenkeliebau** [comment]
I believe that is in the spotless plugin and configured to use the google java codestyle here: https://github.com/stackabletech/hdfs-topology-provider/pull/4/files#diff-9c5fb3d1b7e3b0f54bc5c4182965c4fe1f9023d449017cece3005d3f90e8e4d8R207

**Comment by lfrancke** [comment]
That's right! I like how in Rust there are no discussions about code style and everyone just hates some of it.
Spotless achieves the same for Java. 

So, I suggest just setting up your IDE to conform to the google style and be done with it :)

We could add a profile that makes the build fail if it isn't formatted according to spotless rules but...for later I'd say.

**Pull request merged**
